apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: govind-role-binding-tech # RoleBinding Name
  namespace: tech  # NameSpace
subjects:
- kind: User
  name: GB  # User Name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: govind-role-tech # Role Name
  apiGroup: rbac.authorization.k8s.io
